// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LoadingOverlay: typeof import('./src/components/Loading/LoadingOverlay.vue')['default']
    PageContainer: typeof import('./src/components/Page/PageContainer.vue')['default']
    PageContent: typeof import('./src/components/Page/PageContent.vue')['default']
    PageFooter: typeof import('./src/components/Page/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/Page/PageHeader.vue')['default']
    PageNav: typeof import('./src/components/Page/PageNav.vue')['default']
    PageTabbar: typeof import('./src/components/Page/PageTabbar.vue')['default']
    PopupBottom: typeof import('./src/components/Popup/PopupBottom.vue')['default']
    PopupCenter: typeof import('./src/components/Popup/PopupCenter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollAd: typeof import('./src/components/ScrollAd/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanField: typeof import('vant/es')['Field']
    VanInput: typeof import('vant/es')['Input']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
