// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bottom: typeof import('./src/components/popup/bottom.vue')['default']
    BottomScroll: typeof import('./src/components/popup/bottomScroll.vue')['default']
    Center: typeof import('./src/components/popup/center.vue')['default']
    Container: typeof import('./src/components/page/container.vue')['default']
    copy: typeof import('./src/components/popup/bottom copy.vue')['default']
    LoadingOverlay: typeof import('./src/components/Loading/LoadingOverlay.vue')['default']
    Nav: typeof import('./src/components/page/nav.vue')['default']
    Overlay: typeof import('./src/components/loading/overlay.vue')['default']
    PageContainer: typeof import('./src/components/Page/PageContainer.vue')['default']
    PageContent: typeof import('./src/components/Page/PageContent.vue')['default']
    PageFooter: typeof import('./src/components/Page/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/Page/PageHeader.vue')['default']
    PageNav: typeof import('./src/components/Page/PageNav.vue')['default']
    PageTabbar: typeof import('./src/components/Page/PageTabbar.vue')['default']
    PopupBottom: typeof import('./src/components/Popup/PopupBottom.vue')['default']
    PopupCenter: typeof import('./src/components/Popup/PopupCenter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollAd: typeof import('./src/components/ScrollAd/index.vue')['default']
    Skeleton: typeof import('./src/components/skeleton/index.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon.vue')['default']
    Tabbar: typeof import('./src/components/page/tabbar.vue')['default']
    VanBotton: typeof import('vant/es')['Botton']
    VanButton: typeof import('vant/es')['Button']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanInput: typeof import('vant/es')['Input']
    VanList: typeof import('vant/es')['List']
    VanPopup: typeof import('vant/es')['Popup']
    VanSkeleton: typeof import('vant/es')['Skeleton']
  }
}
