// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LoadingOverlay: typeof import('./src/components/Loading/LoadingOverlay.vue')['default']
    PopupBottom: typeof import('./src/components/Popup/PopupBottom.vue')['default']
    PopupCenter: typeof import('./src/components/Popup/PopupCenter.vue')['default']
    PopupScroll: typeof import('./src/components/Popup/PopupScroll.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
